### ISSUE TITLE
Mistake in README example?

### ISSUE THREAD

**Issue by git-afsantos** [robotcaresystems/RoboticsLanguage#58]
The README suggests the use of `--deploy-path` to specify a workspace location, when not using the default, as per the command:

```
rol --deploy-path ~/catkin_ws/src/ RoboticsLanguage/Examples/1_hello_world.rol -c -l
```

I was experimenting with the examples, using a new workspace, within a Python *virtualenv* (although I do not think this matters), and I could not make progress because the generated code was being deployed to the default workspace location, which did not work for `catkin build`.

Digging through the code, I found the `--deploy-ros-cpp-path` option, which was what actually worked for me, as the default output is RosCpp.

In my case, the working command was as follows:

```
rol --deploy-ros-cpp-path ../catkin_ws/src/ -c 9_temporal_logic.rol -v debug
```

So I assume that the `--deploy-path` does not apply for all outputs, and, in that case, should the README be changed to reflect this?

**Comment by gadlopes** [comment]
The parameter `--deploy-path` was added initially as the main deploy path. When we started outputting to ROS2 we needed a new deploy path different from the ROS1 path. So we created more deploy paths for each output. In your `~.rol/parameters.yaml` you can specify your favourite output deploy paths:

```yaml
globals:
  deploy: /home/roboticslanguage/deploy/
  deployOutputs:
    Ros2Cpp: /home/roboticslanguage/ros2_ws/src/
    RosCpp: /home/roboticslanguage/catkin_ws/src/
```

I will change the documentation to make sure this is clear. Thanks!!!
